/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "agent.baml": "class DoneForNow {\n  intent \"done_for_now\" @description(\"Always 'done_for_now'\")\n  message string @description(\"The response to send back to the user\")\n}\n\nfunction DetermineNextStep(input: string) -> DoneForNow {\n  client Gemini\n  prompt #\"\n    You are Joe a helpful AI assistant. Respond to the user's message.\n\n    {{ input }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
  "clients.baml": "client<llm> Gemini {\n  provider google-ai\n  options {\n    model \"gemini-2.5-flash\"\n  }\n}\n",
  "generators.baml": "generator target {\n  output_type \"typescript\"\n  output_dir \"../\"\n  default_client_mode \"async\"\n  version \"0.219.0\"\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}