/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CalendarDone,  CheckAvailability,  CreateEvent,  DeleteEvent,  GetEvent,  ListEvents,  QuickAdd,  RequestInfo,  UpdateEvent } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CalendarDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface CheckAvailability {
      intent?: "check_availability" | null
      date?: string | null
      startTime?: string | null
      endTime?: string | null
      timezone?: string | null
    }
    export interface CreateEvent {
      intent?: "create_event" | null
      summary?: string | null
      date?: string | null
      startTime?: string | null
      endTime?: string | null
      description?: string | null
      location?: string | null
      timezone?: string | null
    }
    export interface DeleteEvent {
      intent?: "delete_event" | null
      eventId?: string | null
      confirmation?: string | null
    }
    export interface GetEvent {
      intent?: "get_event" | null
      eventId?: string | null
    }
    export interface ListEvents {
      intent?: "list_events" | null
      date?: string | null
      timezone?: string | null
    }
    export interface QuickAdd {
      intent?: "quick_add" | null
      text?: string | null
    }
    export interface RequestInfo {
      intent?: "request_info" | null
      message?: string | null
    }
    export interface UpdateEvent {
      intent?: "update_event" | null
      eventId?: string | null
      summary?: string | null
      date?: string | null
      startTime?: string | null
      endTime?: string | null
      description?: string | null
      location?: string | null
      timezone?: string | null
    }
export type CalendarStep = CreateEvent | ListEvents | GetEvent | UpdateEvent | DeleteEvent | CheckAvailability | QuickAdd | RequestInfo | CalendarDone | null

}