/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface CalendarDone {
  intent: "done"
  message: string
  
}

export interface CheckAvailability {
  intent: "check_availability"
  date: string
  startTime: string
  endTime: string
  timezone: string
  
}

export interface CreateEvent {
  intent: "create_event"
  summary: string
  date: string
  startTime: string
  endTime: string
  description: string
  location?: string | null
  timezone: string
  
}

export interface DeleteEvent {
  intent: "delete_event"
  eventId: string
  confirmation: string
  
}

export interface GetEvent {
  intent: "get_event"
  eventId: string
  
}

export interface ListEvents {
  intent: "list_events"
  date: string
  timezone: string
  
}

export interface QuickAdd {
  intent: "quick_add"
  text: string
  
}

export interface RequestInfo {
  intent: "request_info"
  message: string
  
}

export interface UpdateEvent {
  intent: "update_event"
  eventId: string
  summary?: string | null
  date?: string | null
  startTime?: string | null
  endTime?: string | null
  description?: string | null
  location?: string | null
  timezone: string
  
}

export type CalendarStep = CreateEvent | ListEvents | GetEvent | UpdateEvent | DeleteEvent | CheckAvailability | QuickAdd | RequestInfo | CalendarDone
