/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CreateDocument,  DocsDone,  DocsRequestInfo,  GetDocument,  InsertText,  ListDocuments,  ReplaceText } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CreateDocument {
      intent?: "create_document" | null
      title?: string | null
      content?: string | null
    }
    export interface DocsDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface DocsRequestInfo {
      intent?: "request_info" | null
      message?: string | null
    }
    export interface GetDocument {
      intent?: "get_document" | null
      documentId?: string | null
    }
    export interface InsertText {
      intent?: "insert_text" | null
      documentId?: string | null
      text?: string | null
      position?: string | null
    }
    export interface ListDocuments {
      intent?: "list_documents" | null
      query?: string | null
    }
    export interface ReplaceText {
      intent?: "replace_text" | null
      documentId?: string | null
      find?: string | null
      replaceWith?: string | null
    }
export type DocsStep = CreateDocument | GetDocument | InsertText | ReplaceText | ListDocuments | DocsRequestInfo | DocsDone | null

}