/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CreateMeeting,  EndMeeting,  GetMeeting,  GetTranscriptEntries,  ListConferences,  ListRecordings,  ListTranscripts,  MeetDone,  MeetRequestInfo } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CreateMeeting {
      intent?: "create_meeting" | null
    }
    export interface EndMeeting {
      intent?: "end_meeting" | null
      spaceName?: string | null
    }
    export interface GetMeeting {
      intent?: "get_meeting" | null
      spaceName?: string | null
    }
    export interface GetTranscriptEntries {
      intent?: "get_transcript_entries" | null
      transcriptName?: string | null
    }
    export interface ListConferences {
      intent?: "list_conferences" | null
      pageSize?: number | null
    }
    export interface ListRecordings {
      intent?: "list_recordings" | null
      conferenceRecordName?: string | null
    }
    export interface ListTranscripts {
      intent?: "list_transcripts" | null
      conferenceRecordName?: string | null
    }
    export interface MeetDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface MeetRequestInfo {
      intent?: "request_info" | null
      message?: string | null
    }
export type MeetStep = CreateMeeting | GetMeeting | EndMeeting | ListConferences | ListRecordings | ListTranscripts | GetTranscriptEntries | MeetRequestInfo | MeetDone | null

}