/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "agent.baml": "class DoneForNow {\n  intent \"done_for_now\" @description(\"Respond directly to the user — ONLY for greetings, questions, chat, or things none of the specialist agents can handle\")\n  message string @description(\"The response to send back to the user\")\n}\n\nclass Handoff {\n  intent \"handoff\" @description(\"Hand off to a specialist agent\")\n  agent \"calendar\" | \"gmail\" | \"docs\" | \"sheets\" | \"meet\" @description(\"'calendar' for scheduling/events, 'gmail' for email, 'docs' for Google Docs, 'sheets' for spreadsheets, 'meet' for video calls\")\n  task string @description(\"The task to hand off, rephrased clearly from the user's message\")\n}\n\ntype RouterStep = DoneForNow | Handoff\n\nfunction DetermineNextStep(thread: string, lastMessage: string) -> RouterStep {\n  client Gemini\n  prompt #\"\n    You are Joe, a helpful AI assistant on Discord.\n\n    You can help with these services — ALWAYS hand off when a request matches one:\n    - calendar: scheduling, events, meetings, availability, reminders\n    - gmail: reading, sending, replying, drafting, searching email\n    - docs: creating, reading, editing Google Docs or documents\n    - sheets: creating, reading, writing Google Spreadsheets or tabular data\n    - meet: creating video calls, listing meetings, recordings, transcripts\n\n    If the user's request matches ANY of the above, use handoff. Only use done_for_now for greetings, general chat, or requests that don't match any agent.\n\n    {% if thread %}\n    Here is the conversation so far:\n    {{ thread }}\n    {% endif %}\n\n    Latest message: {{ lastMessage }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
  "clients.baml": "client<llm> Gemini {\n  provider google-ai\n  options {\n    model \"gemini-2.5-flash\"\n  }\n}\n",
  "generators.baml": "generator target {\n  output_type \"typescript\"\n  output_dir \"../\"\n  default_client_mode \"async\"\n  version \"0.219.0\"\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}