/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  DoneForNow,  GWorkspaceDone,  GWorkspaceRequestInfo,  Handoff,  RunCalendar,  RunDocs,  RunDrive,  RunGmail,  RunMeet,  RunSheets } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface DoneForNow {
      intent?: "done_for_now" | null
      message?: string | null
    }
    export interface GWorkspaceDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface GWorkspaceRequestInfo {
      intent?: "request_info" | null
      question?: string | null
    }
    export interface Handoff {
      intent?: "handoff" | null
      agent?: "gworkspace" | null
      task?: string | null
    }
    export interface RunCalendar {
      intent?: "run_calendar" | null
      task?: string | null
    }
    export interface RunDocs {
      intent?: "run_docs" | null
      task?: string | null
    }
    export interface RunDrive {
      intent?: "run_drive" | null
      task?: string | null
    }
    export interface RunGmail {
      intent?: "run_gmail" | null
      task?: string | null
    }
    export interface RunMeet {
      intent?: "run_meet" | null
      task?: string | null
    }
    export interface RunSheets {
      intent?: "run_sheets" | null
      task?: string | null
    }
export type GWorkspaceStep = RunCalendar | RunGmail | RunDocs | RunSheets | RunMeet | RunDrive | GWorkspaceRequestInfo | GWorkspaceDone | null

export type RouterStep = DoneForNow | Handoff | null

}