/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AddSheet: ClassViewer<'AddSheet', "intent" | "spreadsheetId" | "title">;
    
    AppendRows: ClassViewer<'AppendRows', "intent" | "spreadsheetId" | "range" | "values">;
    
    ArchiveEmail: ClassViewer<'ArchiveEmail', "intent" | "messageId">;
    
    CheckAvailability: ClassViewer<'CheckAvailability', "intent" | "date" | "startTime" | "endTime" | "timezone">;
    
    ClearRange: ClassViewer<'ClearRange', "intent" | "spreadsheetId" | "range">;
    
    CompleteStep: ClassViewer<'CompleteStep', "intent" | "summary">;
    
    CopyFile: ClassViewer<'CopyFile', "intent" | "fileId" | "newName" | "destinationFolderId">;
    
    CreateDocument: ClassViewer<'CreateDocument', "intent" | "title" | "content">;
    
    CreateDraft: ClassViewer<'CreateDraft', "intent" | "to" | "subject" | "body">;
    
    CreateEvent: ClassViewer<'CreateEvent', "intent" | "summary" | "date" | "startTime" | "endTime" | "description" | "location" | "timezone">;
    
    CreateFolder: ClassViewer<'CreateFolder', "intent" | "name" | "parentId">;
    
    CreateMeeting: ClassViewer<'CreateMeeting', "intent">;
    
    CreateSpreadsheet: ClassViewer<'CreateSpreadsheet', "intent" | "title">;
    
    DeleteEvent: ClassViewer<'DeleteEvent', "intent" | "eventId" | "confirmation">;
    
    Done: ClassViewer<'Done', "intent" | "message">;
    
    EndMeeting: ClassViewer<'EndMeeting', "intent" | "spaceName">;
    
    FormatParagraph: ClassViewer<'FormatParagraph', "intent" | "documentId" | "target" | "headingLevel" | "alignment" | "bulletType">;
    
    FormatText: ClassViewer<'FormatText', "intent" | "documentId" | "target" | "bold" | "italic" | "underline" | "fontSize" | "fontFamily">;
    
    ForwardEmail: ClassViewer<'ForwardEmail', "intent" | "messageId" | "to" | "comment">;
    
    GetDocument: ClassViewer<'GetDocument', "intent" | "documentId">;
    
    GetEvent: ClassViewer<'GetEvent', "intent" | "eventId">;
    
    GetFile: ClassViewer<'GetFile', "intent" | "fileId">;
    
    GetMeeting: ClassViewer<'GetMeeting', "intent" | "spaceName">;
    
    GetSpreadsheet: ClassViewer<'GetSpreadsheet', "intent" | "spreadsheetId">;
    
    GetTranscriptEntries: ClassViewer<'GetTranscriptEntries', "intent" | "transcriptName">;
    
    InsertText: ClassViewer<'InsertText', "intent" | "documentId" | "text" | "position">;
    
    ListConferences: ClassViewer<'ListConferences', "intent" | "pageSize">;
    
    ListDocuments: ClassViewer<'ListDocuments', "intent" | "query">;
    
    ListEmails: ClassViewer<'ListEmails', "intent" | "query" | "maxResults">;
    
    ListEvents: ClassViewer<'ListEvents', "intent" | "date" | "timezone">;
    
    ListPermissions: ClassViewer<'ListPermissions', "intent" | "fileId">;
    
    ListRecordings: ClassViewer<'ListRecordings', "intent" | "conferenceRecordName">;
    
    ListSpreadsheets: ClassViewer<'ListSpreadsheets', "intent" | "query">;
    
    ListTranscripts: ClassViewer<'ListTranscripts', "intent" | "conferenceRecordName">;
    
    MarkRead: ClassViewer<'MarkRead', "intent" | "messageId">;
    
    MarkUnread: ClassViewer<'MarkUnread', "intent" | "messageId">;
    
    ModifyLabels: ClassViewer<'ModifyLabels', "intent" | "messageId" | "addLabels" | "removeLabels">;
    
    MoveFile: ClassViewer<'MoveFile', "intent" | "fileId" | "destinationFolderId">;
    
    Plan: ClassViewer<'Plan', "goal" | "steps">;
    
    PlanStep: ClassViewer<'PlanStep', "id" | "title" | "success">;
    
    QuickAdd: ClassViewer<'QuickAdd', "intent" | "text">;
    
    ReadEmail: ClassViewer<'ReadEmail', "intent" | "messageId">;
    
    ReadValues: ClassViewer<'ReadValues', "intent" | "spreadsheetId" | "range">;
    
    RenameFile: ClassViewer<'RenameFile', "intent" | "fileId" | "newName">;
    
    ReplaceText: ClassViewer<'ReplaceText', "intent" | "documentId" | "find" | "replaceWith">;
    
    ReplyToEmail: ClassViewer<'ReplyToEmail', "intent" | "messageId" | "body">;
    
    RequestInfo: ClassViewer<'RequestInfo', "intent" | "message">;
    
    SaveMemory: ClassViewer<'SaveMemory', "intent" | "note">;
    
    SearchFiles: ClassViewer<'SearchFiles', "intent" | "query" | "mimeTypeFilter" | "folderId" | "maxResults">;
    
    SendEmail: ClassViewer<'SendEmail', "intent" | "to" | "subject" | "body">;
    
    ShareFile: ClassViewer<'ShareFile', "intent" | "fileId" | "shareType" | "role" | "emailOrDomain" | "sendNotification">;
    
    StarEmail: ClassViewer<'StarEmail', "intent" | "messageId">;
    
    TrashEmail: ClassViewer<'TrashEmail', "intent" | "messageId">;
    
    TrashFile: ClassViewer<'TrashFile', "intent" | "fileId" | "confirmation">;
    
    UnstarEmail: ClassViewer<'UnstarEmail', "intent" | "messageId">;
    
    UpdateEvent: ClassViewer<'UpdateEvent', "intent" | "eventId" | "summary" | "date" | "startTime" | "endTime" | "description" | "location" | "timezone">;
    
    WriteValues: ClassViewer<'WriteValues', "intent" | "spreadsheetId" | "range" | "values">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AddSheet","AppendRows","ArchiveEmail","CheckAvailability","ClearRange","CompleteStep","CopyFile","CreateDocument","CreateDraft","CreateEvent","CreateFolder","CreateMeeting","CreateSpreadsheet","DeleteEvent","Done","EndMeeting","FormatParagraph","FormatText","ForwardEmail","GetDocument","GetEvent","GetFile","GetMeeting","GetSpreadsheet","GetTranscriptEntries","InsertText","ListConferences","ListDocuments","ListEmails","ListEvents","ListPermissions","ListRecordings","ListSpreadsheets","ListTranscripts","MarkRead","MarkUnread","ModifyLabels","MoveFile","Plan","PlanStep","QuickAdd","ReadEmail","ReadValues","RenameFile","ReplaceText","ReplyToEmail","RequestInfo","SaveMemory","SearchFiles","SendEmail","ShareFile","StarEmail","TrashEmail","TrashFile","UnstarEmail","UpdateEvent","WriteValues",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AddSheet = this.tb.classViewer("AddSheet", [
          "intent","spreadsheetId","title",
        ]);
        
        this.AppendRows = this.tb.classViewer("AppendRows", [
          "intent","spreadsheetId","range","values",
        ]);
        
        this.ArchiveEmail = this.tb.classViewer("ArchiveEmail", [
          "intent","messageId",
        ]);
        
        this.CheckAvailability = this.tb.classViewer("CheckAvailability", [
          "intent","date","startTime","endTime","timezone",
        ]);
        
        this.ClearRange = this.tb.classViewer("ClearRange", [
          "intent","spreadsheetId","range",
        ]);
        
        this.CompleteStep = this.tb.classViewer("CompleteStep", [
          "intent","summary",
        ]);
        
        this.CopyFile = this.tb.classViewer("CopyFile", [
          "intent","fileId","newName","destinationFolderId",
        ]);
        
        this.CreateDocument = this.tb.classViewer("CreateDocument", [
          "intent","title","content",
        ]);
        
        this.CreateDraft = this.tb.classViewer("CreateDraft", [
          "intent","to","subject","body",
        ]);
        
        this.CreateEvent = this.tb.classViewer("CreateEvent", [
          "intent","summary","date","startTime","endTime","description","location","timezone",
        ]);
        
        this.CreateFolder = this.tb.classViewer("CreateFolder", [
          "intent","name","parentId",
        ]);
        
        this.CreateMeeting = this.tb.classViewer("CreateMeeting", [
          "intent",
        ]);
        
        this.CreateSpreadsheet = this.tb.classViewer("CreateSpreadsheet", [
          "intent","title",
        ]);
        
        this.DeleteEvent = this.tb.classViewer("DeleteEvent", [
          "intent","eventId","confirmation",
        ]);
        
        this.Done = this.tb.classViewer("Done", [
          "intent","message",
        ]);
        
        this.EndMeeting = this.tb.classViewer("EndMeeting", [
          "intent","spaceName",
        ]);
        
        this.FormatParagraph = this.tb.classViewer("FormatParagraph", [
          "intent","documentId","target","headingLevel","alignment","bulletType",
        ]);
        
        this.FormatText = this.tb.classViewer("FormatText", [
          "intent","documentId","target","bold","italic","underline","fontSize","fontFamily",
        ]);
        
        this.ForwardEmail = this.tb.classViewer("ForwardEmail", [
          "intent","messageId","to","comment",
        ]);
        
        this.GetDocument = this.tb.classViewer("GetDocument", [
          "intent","documentId",
        ]);
        
        this.GetEvent = this.tb.classViewer("GetEvent", [
          "intent","eventId",
        ]);
        
        this.GetFile = this.tb.classViewer("GetFile", [
          "intent","fileId",
        ]);
        
        this.GetMeeting = this.tb.classViewer("GetMeeting", [
          "intent","spaceName",
        ]);
        
        this.GetSpreadsheet = this.tb.classViewer("GetSpreadsheet", [
          "intent","spreadsheetId",
        ]);
        
        this.GetTranscriptEntries = this.tb.classViewer("GetTranscriptEntries", [
          "intent","transcriptName",
        ]);
        
        this.InsertText = this.tb.classViewer("InsertText", [
          "intent","documentId","text","position",
        ]);
        
        this.ListConferences = this.tb.classViewer("ListConferences", [
          "intent","pageSize",
        ]);
        
        this.ListDocuments = this.tb.classViewer("ListDocuments", [
          "intent","query",
        ]);
        
        this.ListEmails = this.tb.classViewer("ListEmails", [
          "intent","query","maxResults",
        ]);
        
        this.ListEvents = this.tb.classViewer("ListEvents", [
          "intent","date","timezone",
        ]);
        
        this.ListPermissions = this.tb.classViewer("ListPermissions", [
          "intent","fileId",
        ]);
        
        this.ListRecordings = this.tb.classViewer("ListRecordings", [
          "intent","conferenceRecordName",
        ]);
        
        this.ListSpreadsheets = this.tb.classViewer("ListSpreadsheets", [
          "intent","query",
        ]);
        
        this.ListTranscripts = this.tb.classViewer("ListTranscripts", [
          "intent","conferenceRecordName",
        ]);
        
        this.MarkRead = this.tb.classViewer("MarkRead", [
          "intent","messageId",
        ]);
        
        this.MarkUnread = this.tb.classViewer("MarkUnread", [
          "intent","messageId",
        ]);
        
        this.ModifyLabels = this.tb.classViewer("ModifyLabels", [
          "intent","messageId","addLabels","removeLabels",
        ]);
        
        this.MoveFile = this.tb.classViewer("MoveFile", [
          "intent","fileId","destinationFolderId",
        ]);
        
        this.Plan = this.tb.classViewer("Plan", [
          "goal","steps",
        ]);
        
        this.PlanStep = this.tb.classViewer("PlanStep", [
          "id","title","success",
        ]);
        
        this.QuickAdd = this.tb.classViewer("QuickAdd", [
          "intent","text",
        ]);
        
        this.ReadEmail = this.tb.classViewer("ReadEmail", [
          "intent","messageId",
        ]);
        
        this.ReadValues = this.tb.classViewer("ReadValues", [
          "intent","spreadsheetId","range",
        ]);
        
        this.RenameFile = this.tb.classViewer("RenameFile", [
          "intent","fileId","newName",
        ]);
        
        this.ReplaceText = this.tb.classViewer("ReplaceText", [
          "intent","documentId","find","replaceWith",
        ]);
        
        this.ReplyToEmail = this.tb.classViewer("ReplyToEmail", [
          "intent","messageId","body",
        ]);
        
        this.RequestInfo = this.tb.classViewer("RequestInfo", [
          "intent","message",
        ]);
        
        this.SaveMemory = this.tb.classViewer("SaveMemory", [
          "intent","note",
        ]);
        
        this.SearchFiles = this.tb.classViewer("SearchFiles", [
          "intent","query","mimeTypeFilter","folderId","maxResults",
        ]);
        
        this.SendEmail = this.tb.classViewer("SendEmail", [
          "intent","to","subject","body",
        ]);
        
        this.ShareFile = this.tb.classViewer("ShareFile", [
          "intent","fileId","shareType","role","emailOrDomain","sendNotification",
        ]);
        
        this.StarEmail = this.tb.classViewer("StarEmail", [
          "intent","messageId",
        ]);
        
        this.TrashEmail = this.tb.classViewer("TrashEmail", [
          "intent","messageId",
        ]);
        
        this.TrashFile = this.tb.classViewer("TrashFile", [
          "intent","fileId","confirmation",
        ]);
        
        this.UnstarEmail = this.tb.classViewer("UnstarEmail", [
          "intent","messageId",
        ]);
        
        this.UpdateEvent = this.tb.classViewer("UpdateEvent", [
          "intent","eventId","summary","date","startTime","endTime","description","location","timezone",
        ]);
        
        this.WriteValues = this.tb.classViewer("WriteValues", [
          "intent","spreadsheetId","range","values",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}