/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AddSheet {
  intent: "add_sheet"
  spreadsheetId: string
  title: string
  
}

export interface AppendRows {
  intent: "append_rows"
  spreadsheetId: string
  range: string
  values: string[][]
  
}

export interface ArchiveEmail {
  intent: "archive_email"
  messageId: string
  
}

export interface CheckAvailability {
  intent: "check_availability"
  date: string
  startTime: string
  endTime: string
  timezone: string
  
}

export interface ClearRange {
  intent: "clear_range"
  spreadsheetId: string
  range: string
  
}

export interface CopyFile {
  intent: "copy_file"
  fileId: string
  newName?: string | null
  destinationFolderId?: string | null
  
}

export interface CreateDocument {
  intent: "create_document"
  title: string
  content?: string | null
  
}

export interface CreateDraft {
  intent: "create_draft"
  to: string
  subject: string
  body: string
  
}

export interface CreateEvent {
  intent: "create_event"
  summary: string
  date: string
  startTime: string
  endTime: string
  description: string
  location?: string | null
  timezone: string
  
}

export interface CreateFolder {
  intent: "create_folder"
  name: string
  parentId?: string | null
  
}

export interface CreateMeeting {
  intent: "create_meeting"
  
}

export interface CreateSpreadsheet {
  intent: "create_spreadsheet"
  title: string
  
}

export interface DeleteEvent {
  intent: "delete_event"
  eventId: string
  confirmation: string
  
}

export interface Done {
  intent: "done"
  message: string
  
}

export interface EndMeeting {
  intent: "end_meeting"
  spaceName: string
  
}

export interface FormatParagraph {
  intent: "format_paragraph"
  documentId: string
  target: string
  headingLevel?: number | null
  alignment?: string | null
  bulletType?: string | null
  
}

export interface FormatText {
  intent: "format_text"
  documentId: string
  target: string
  bold?: boolean | null
  italic?: boolean | null
  underline?: boolean | null
  fontSize?: number | null
  fontFamily?: string | null
  
}

export interface ForwardEmail {
  intent: "forward_email"
  messageId: string
  to: string
  comment?: string | null
  
}

export interface GetDocument {
  intent: "get_document"
  documentId: string
  
}

export interface GetEvent {
  intent: "get_event"
  eventId: string
  
}

export interface GetFile {
  intent: "get_file"
  fileId: string
  
}

export interface GetMeeting {
  intent: "get_meeting"
  spaceName: string
  
}

export interface GetSpreadsheet {
  intent: "get_spreadsheet"
  spreadsheetId: string
  
}

export interface GetTranscriptEntries {
  intent: "get_transcript_entries"
  transcriptName: string
  
}

export interface InsertText {
  intent: "insert_text"
  documentId: string
  text: string
  position: string
  
}

export interface ListConferences {
  intent: "list_conferences"
  pageSize?: number | null
  
}

export interface ListDocuments {
  intent: "list_documents"
  query: string
  
}

export interface ListEmails {
  intent: "list_emails"
  query: string
  maxResults?: number | null
  
}

export interface ListEvents {
  intent: "list_events"
  date: string
  timezone: string
  
}

export interface ListPermissions {
  intent: "list_permissions"
  fileId: string
  
}

export interface ListRecordings {
  intent: "list_recordings"
  conferenceRecordName: string
  
}

export interface ListSpreadsheets {
  intent: "list_spreadsheets"
  query: string
  
}

export interface ListTranscripts {
  intent: "list_transcripts"
  conferenceRecordName: string
  
}

export interface MarkRead {
  intent: "mark_read"
  messageId: string
  
}

export interface MarkUnread {
  intent: "mark_unread"
  messageId: string
  
}

export interface ModifyLabels {
  intent: "modify_labels"
  messageId: string
  addLabels: string[]
  removeLabels: string[]
  
}

export interface MoveFile {
  intent: "move_file"
  fileId: string
  destinationFolderId: string
  
}

export interface QuickAdd {
  intent: "quick_add"
  text: string
  
}

export interface ReadEmail {
  intent: "read_email"
  messageId: string
  
}

export interface ReadValues {
  intent: "read_values"
  spreadsheetId: string
  range: string
  
}

export interface RenameFile {
  intent: "rename_file"
  fileId: string
  newName: string
  
}

export interface ReplaceText {
  intent: "replace_text"
  documentId: string
  find: string
  replaceWith: string
  
}

export interface ReplyToEmail {
  intent: "reply_to_email"
  messageId: string
  body: string
  
}

export interface RequestInfo {
  intent: "request_info"
  message: string
  
}

export interface SearchFiles {
  intent: "search_files"
  query?: string | null
  mimeTypeFilter?: string | null
  folderId?: string | null
  maxResults?: number | null
  
}

export interface SendEmail {
  intent: "send_email"
  to: string
  subject: string
  body: string
  
}

export interface ShareFile {
  intent: "share_file"
  fileId: string
  shareType: string
  role: string
  emailOrDomain?: string | null
  sendNotification?: boolean | null
  
}

export interface StarEmail {
  intent: "star_email"
  messageId: string
  
}

export interface TrashEmail {
  intent: "trash_email"
  messageId: string
  
}

export interface TrashFile {
  intent: "trash_file"
  fileId: string
  confirmation: string
  
}

export interface UnstarEmail {
  intent: "unstar_email"
  messageId: string
  
}

export interface UpdateEvent {
  intent: "update_event"
  eventId: string
  summary?: string | null
  date?: string | null
  startTime?: string | null
  endTime?: string | null
  description?: string | null
  location?: string | null
  timezone: string
  
}

export interface WriteValues {
  intent: "write_values"
  spreadsheetId: string
  range: string
  values: string[][]
  
}

export type AgentStep = RequestInfo | Done | CreateEvent | ListEvents | GetEvent | UpdateEvent | DeleteEvent | CheckAvailability | QuickAdd | ListEmails | ReadEmail | SendEmail | ReplyToEmail | ForwardEmail | CreateDraft | ArchiveEmail | TrashEmail | MarkRead | MarkUnread | StarEmail | UnstarEmail | ModifyLabels | CreateSpreadsheet | GetSpreadsheet | ReadValues | WriteValues | AppendRows | ClearRange | AddSheet | ListSpreadsheets | CreateDocument | GetDocument | InsertText | ReplaceText | ListDocuments | FormatText | FormatParagraph | SearchFiles | GetFile | CreateFolder | MoveFile | CopyFile | RenameFile | TrashFile | ShareFile | ListPermissions | CreateMeeting | GetMeeting | EndMeeting | ListConferences | ListRecordings | ListTranscripts | GetTranscriptEntries
