/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AddSheet,  AppendRows,  ClearRange,  CreateSpreadsheet,  GetSpreadsheet,  ListSpreadsheets,  ReadValues,  SheetsDone,  SheetsRequestInfo,  WriteValues } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AddSheet {
      intent?: "add_sheet" | null
      spreadsheetId?: string | null
      title?: string | null
    }
    export interface AppendRows {
      intent?: "append_rows" | null
      spreadsheetId?: string | null
      range?: string | null
      values: string[][]
    }
    export interface ClearRange {
      intent?: "clear_range" | null
      spreadsheetId?: string | null
      range?: string | null
    }
    export interface CreateSpreadsheet {
      intent?: "create_spreadsheet" | null
      title?: string | null
    }
    export interface GetSpreadsheet {
      intent?: "get_spreadsheet" | null
      spreadsheetId?: string | null
    }
    export interface ListSpreadsheets {
      intent?: "list_spreadsheets" | null
      query?: string | null
    }
    export interface ReadValues {
      intent?: "read_values" | null
      spreadsheetId?: string | null
      range?: string | null
    }
    export interface SheetsDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface SheetsRequestInfo {
      intent?: "request_info" | null
      message?: string | null
    }
    export interface WriteValues {
      intent?: "write_values" | null
      spreadsheetId?: string | null
      range?: string | null
      values: string[][]
    }
export type SheetsStep = CreateSpreadsheet | GetSpreadsheet | ReadValues | WriteValues | AppendRows | ClearRange | AddSheet | ListSpreadsheets | SheetsRequestInfo | SheetsDone | null

}