/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AddSheet: ClassViewer<'AddSheet', "intent" | "spreadsheetId" | "title">;
    
    AppendRows: ClassViewer<'AppendRows', "intent" | "spreadsheetId" | "range" | "values">;
    
    ClearRange: ClassViewer<'ClearRange', "intent" | "spreadsheetId" | "range">;
    
    CreateSpreadsheet: ClassViewer<'CreateSpreadsheet', "intent" | "title">;
    
    GetSpreadsheet: ClassViewer<'GetSpreadsheet', "intent" | "spreadsheetId">;
    
    ListSpreadsheets: ClassViewer<'ListSpreadsheets', "intent" | "query">;
    
    ReadValues: ClassViewer<'ReadValues', "intent" | "spreadsheetId" | "range">;
    
    SheetsDone: ClassViewer<'SheetsDone', "intent" | "message">;
    
    SheetsRequestInfo: ClassViewer<'SheetsRequestInfo', "intent" | "message">;
    
    WriteValues: ClassViewer<'WriteValues', "intent" | "spreadsheetId" | "range" | "values">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AddSheet","AppendRows","ClearRange","CreateSpreadsheet","GetSpreadsheet","ListSpreadsheets","ReadValues","SheetsDone","SheetsRequestInfo","WriteValues",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AddSheet = this.tb.classViewer("AddSheet", [
          "intent","spreadsheetId","title",
        ]);
        
        this.AppendRows = this.tb.classViewer("AppendRows", [
          "intent","spreadsheetId","range","values",
        ]);
        
        this.ClearRange = this.tb.classViewer("ClearRange", [
          "intent","spreadsheetId","range",
        ]);
        
        this.CreateSpreadsheet = this.tb.classViewer("CreateSpreadsheet", [
          "intent","title",
        ]);
        
        this.GetSpreadsheet = this.tb.classViewer("GetSpreadsheet", [
          "intent","spreadsheetId",
        ]);
        
        this.ListSpreadsheets = this.tb.classViewer("ListSpreadsheets", [
          "intent","query",
        ]);
        
        this.ReadValues = this.tb.classViewer("ReadValues", [
          "intent","spreadsheetId","range",
        ]);
        
        this.SheetsDone = this.tb.classViewer("SheetsDone", [
          "intent","message",
        ]);
        
        this.SheetsRequestInfo = this.tb.classViewer("SheetsRequestInfo", [
          "intent","message",
        ]);
        
        this.WriteValues = this.tb.classViewer("WriteValues", [
          "intent","spreadsheetId","range","values",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}