/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CopyFile,  CreateFolder,  DriveDone,  GetFile,  ListPermissions,  MoveFile,  RenameFile,  RequestInfo,  SearchFiles,  ShareFile,  TrashFile } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CopyFile {
      intent?: "copy_file" | null
      fileId?: string | null
      newName?: string | null
      destinationFolderId?: string | null
    }
    export interface CreateFolder {
      intent?: "create_folder" | null
      name?: string | null
      parentId?: string | null
    }
    export interface DriveDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface GetFile {
      intent?: "get_file" | null
      fileId?: string | null
    }
    export interface ListPermissions {
      intent?: "list_permissions" | null
      fileId?: string | null
    }
    export interface MoveFile {
      intent?: "move_file" | null
      fileId?: string | null
      destinationFolderId?: string | null
    }
    export interface RenameFile {
      intent?: "rename_file" | null
      fileId?: string | null
      newName?: string | null
    }
    export interface RequestInfo {
      intent?: "request_info" | null
      message?: string | null
    }
    export interface SearchFiles {
      intent?: "search_files" | null
      query?: string | null
      mimeTypeFilter?: string | null
      folderId?: string | null
      maxResults?: number | null
    }
    export interface ShareFile {
      intent?: "share_file" | null
      fileId?: string | null
      shareType?: string | null
      role?: string | null
      emailOrDomain?: string | null
      sendNotification?: boolean | null
    }
    export interface TrashFile {
      intent?: "trash_file" | null
      fileId?: string | null
      confirmation?: string | null
    }
export type DriveStep = SearchFiles | GetFile | CreateFolder | MoveFile | CopyFile | RenameFile | TrashFile | ShareFile | ListPermissions | RequestInfo | DriveDone | null

}