/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface CopyFile {
  intent: "copy_file"
  fileId: string
  newName?: string | null
  destinationFolderId?: string | null
  
}

export interface CreateFolder {
  intent: "create_folder"
  name: string
  parentId?: string | null
  
}

export interface DriveDone {
  intent: "done"
  message: string
  
}

export interface GetFile {
  intent: "get_file"
  fileId: string
  
}

export interface ListPermissions {
  intent: "list_permissions"
  fileId: string
  
}

export interface MoveFile {
  intent: "move_file"
  fileId: string
  destinationFolderId: string
  
}

export interface RenameFile {
  intent: "rename_file"
  fileId: string
  newName: string
  
}

export interface RequestInfo {
  intent: "request_info"
  message: string
  
}

export interface SearchFiles {
  intent: "search_files"
  query?: string | null
  mimeTypeFilter?: string | null
  folderId?: string | null
  maxResults?: number | null
  
}

export interface ShareFile {
  intent: "share_file"
  fileId: string
  shareType: string
  role: string
  emailOrDomain?: string | null
  sendNotification?: boolean | null
  
}

export interface TrashFile {
  intent: "trash_file"
  fileId: string
  confirmation: string
  
}

export type DriveStep = SearchFiles | GetFile | CreateFolder | MoveFile | CopyFile | RenameFile | TrashFile | ShareFile | ListPermissions | RequestInfo | DriveDone
