/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CreateDraft,  GmailDone,  GmailRequestInfo,  ListEmails,  ReadEmail,  ReplyToEmail,  SendEmail } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CreateDraft {
      intent?: "create_draft" | null
      to?: string | null
      subject?: string | null
      body?: string | null
    }
    export interface GmailDone {
      intent?: "done" | null
      message?: string | null
    }
    export interface GmailRequestInfo {
      intent?: "request_info" | null
      message?: string | null
    }
    export interface ListEmails {
      intent?: "list_emails" | null
      query?: string | null
      maxResults?: number | null
    }
    export interface ReadEmail {
      intent?: "read_email" | null
      messageId?: string | null
    }
    export interface ReplyToEmail {
      intent?: "reply_to_email" | null
      messageId?: string | null
      body?: string | null
    }
    export interface SendEmail {
      intent?: "send_email" | null
      to?: string | null
      subject?: string | null
      body?: string | null
    }
export type GmailStep = ListEmails | ReadEmail | SendEmail | ReplyToEmail | CreateDraft | GmailRequestInfo | GmailDone | null

}